# Day 2 Reading Journal

This journal includes several required exercises, but it is meant to encourage active reading more generally.  You should use the journal to take detailed notes, catalog questions, and explore the content from Think Python deeply.

Reading: Think Python Chapter 6.1-6.4, 7

**Due: Thursday, January 28 at 12 noon**



## [Chapter 6.1-6.4](http://www.greenteapress.com/thinkpython/html/thinkpython007.html)

Note: the exercise numbers below match up with the reading for ease of cross referencing.

**Quick check:** What is a _fruitful function_?

A fruitful function is one in which the return statement includes an expression which is immediately returned as a return value. 

### Exercise 1  
Write a `compare` function that returns `1` if `x > y`, `0` if `x == y`, and `-1` if `x < y`.

In [2]:
def comparison(x, y):
	if x > y:
		return 1
	elif x == y:
		return 0
	elif x < y:
		return -1

print comparison(1, 2)

-1


**Quick check:** Modify the `absolute_value` function so that it returns the correct result for all integer inputs.

In [3]:
def absolute_value(x):
    if x < 0:
        return -x
    if x >= 0:
        return x

### Exercise 2  
Use incremental development to write a function called `hypotenuse` that returns the length of the hypotenuse of a right triangle given the lengths of the two legs as arguments. Record each stage of the development process as you go, using as many cells as you need.

In [4]:
def hypotenuse(a, b):
	#square both inputs
	leg1_sq = a**2
	leg2_sq = b**2
	#test that that worked
	print leg1_sq, leg2_sq

hypotenuse(3, 4)

9 16


In [6]:
def hypotenuse(a, b):
	#square both inputs
	leg1_sq = a**2
	leg2_sq = b**2
	#add the legs
	hyp_sq = leg1_sq + leg2_sq
	#test that
	print hyp_sq
    
hypotenuse(3, 4)

25


In [7]:
def hypotenuse(a, b):
	#square both inputs
	leg1_sq = a**2
	leg2_sq = b**2
	#add the legs
	hyp_sq = leg1_sq + leg2_sq
	#take the square root to find the hypotenuse length
	hyp_length = hyp_sq**(1/2)
	return hyp_length

print hypotenuse(3, 4)

1


Why is it returning 1?? I'm confused.

In [8]:
def hypotenuse(a, b):
	#square both inputs
	leg1_sq = a**2
	leg2_sq = b**2
	#add the legs
	hyp_sq = leg1_sq + leg2_sq
	#take the square root to find the hypotenuse length
#	hyp_length = hyp_sq**(1/2)
#	return hyp_length
	#test what **(1/2) is returning
	return leg1_sq**(1/2)

print hypotenuse(3, 4)

1


Ok, that's really confusing. Oh!!! Floats!!! Duh, ok that should make a difference.

In [9]:
def hypotenuse(a, b):
	#square both inputs
	leg1_sq = a**2
	leg2_sq = b**2
	#add the legs
	hyp_sq = leg1_sq + leg2_sq
	#take the square root to find the hypotenuse length
	hyp_length = hyp_sq**0.5
	return hyp_length

print hypotenuse(3, 4)

5.0


Ta-da!!!

### Exercise 3  
Write a function `is_between(x, y, z)` that returns `True` if `x ≤ y ≤ z` or `False` otherwise.

In [10]:
def is_between(x, y, z):
	if x <= y and y <= z:
		return True
	else:
		return False

print is_between(1, 2, 3)

True


## [Chapter 7](http://www.greenteapress.com/thinkpython/html/thinkpython008.html)



**Quick check:** How do you test for equality in Python?

Use ==

Equality is symmetric, whereas assignment is not, and Python uses = for assignment.

**Challenge:** Prove/disprove the Collatz conjecture :)

Has anyone taken the time to try disproving it? Is there any way to actually prove it? The real trick would be to find a pattern within the sequence (other than the given one).

### Exercise 2  
Encapsulate the loop from Section 7.5 in a function called `square_root` that takes `a` as a parameter, chooses a reasonable value of `x`, and returns an estimate of the square root of `a`.

In [18]:
def square_root(a):
	#a is the number to be square-rooted
	x = a / 2.0
	#x is the initial guess as to the output
	epsilon = 0.0000001
	#epsilon is that tiny number suggested in the reading
	while True:
		y = (x + a/x) / 2
		if abs(y-x) < epsilon:
			break
		x = y
	print y

square_root(16)

4.0


### Exercise 3  
To test the square root algorithm you developed in Exercise 2, you could compare it with Python's `math.sqrt` function. Write a function named `test_square_root` that prints a table like this:

```python
1.0 1.0           1.0           0.0
2.0 1.41421356237 1.41421356237 2.22044604925e-16
3.0 1.73205080757 1.73205080757 0.0
4.0 2.0           2.0           0.0
5.0 2.2360679775  2.2360679775  0.0
6.0 2.44948974278 2.44948974278 0.0
7.0 2.64575131106 2.64575131106 0.0
8.0 2.82842712475 2.82842712475 4.4408920985e-16
9.0 3.0           3.0           0.0
```

The first column is a number, `a`; the second column is the square root of a computed with the function from Section 7.5; the third column is the square root computed by `math.sqrt`; the fourth column is the absolute value of the difference between the two estimates.

In [21]:
import math
import numpy as np

#the first column is together in a list, used as function input
NOs = [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]

def test_square_root(NOs):
	#establish an empty list for the second column
	sqt_mine = []
	#this fills that list
	for item in NOs:
		sqt_mine.append(square_root(item))
	#repeating for the third column
	sqt_math = []
	for item in NOs:
		sqt_math.append(math.sqrt(item))
	#aaaand finally, the last column...
	col4 = []
	for i in range(0, len(NOs)):
		first = sqt_math[i]
		second = sqt_mine[i]
		col4.append(first-second)
	#now to turn it all into a single array
	matrix1 = np.matrix([NOs, sqt_mine, sqt_math, col4])
	#transpose it so the lists I made are columns, not rows
	matrix_final = np.transpose(matrix1)
	print matrix_final

test_square_root(NOs)

[[  1.00000000e+00   1.00000000e+00   1.00000000e+00   0.00000000e+00]
 [  2.00000000e+00   1.41421356e+00   1.41421356e+00   2.22044605e-16]
 [  3.00000000e+00   1.73205081e+00   1.73205081e+00   0.00000000e+00]
 [  4.00000000e+00   2.00000000e+00   2.00000000e+00   0.00000000e+00]
 [  5.00000000e+00   2.23606798e+00   2.23606798e+00   0.00000000e+00]
 [  6.00000000e+00   2.44948974e+00   2.44948974e+00   0.00000000e+00]
 [  7.00000000e+00   2.64575131e+00   2.64575131e+00   0.00000000e+00]
 [  8.00000000e+00   2.82842712e+00   2.82842712e+00   4.44089210e-16]
 [  9.00000000e+00   3.00000000e+00   3.00000000e+00   0.00000000e+00]]


### Challenge: Exercise 5  (optional)
The mathematician Srinivasa Ramanujan found an infinite series that can be used to generate a numerical approximation of
$\frac{1}{\pi}$:

$$\frac{1}{\pi} = \frac{2 \sqrt{2}}{9801} \sum_{k=0}^{\infty} \frac{(4k)! (1103+26390k)}{(k!)^4 396^{4k}}$$
 
Write a function called `estimate_pi` that uses this formula to compute and return an estimate of $\pi$. It should use a `while` loop to compute terms of the summation until the last term is smaller than `1e-15` (which is Python notation for $10^{−15}$). You can check the result by comparing it to `math.pi`.

[Possible solution](http://thinkpython.com/code/pi.py) (give the exercise a try before viewing the solution)

## Reading Journal feedback

Have any comments on this Reading Journal? Feel free to leave them below and we'll read them when you submit your journal entry. This could include suggestions to improve the exercises, topics you'd like to see covered in class next time, or other feedback.

If you have Python questions or run into problems while completing the reading, you should post them to Piazza instead so you can get a quick response before your journal is submitted.